name: Run Apprenticeship Scripts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
          

      - name: Install Dependencies
        run: npm install
        
      - name: Set Date Environment Variable
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Start Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh && sudo tailscale up --auth-key=${{ secrets.TAILSCALE_AUTH_KEY }}
          sudo tailscale set --exit-node=${{ secrets.EXIT_NODE_IP }}
    
      - name: Run Scripts
        env:
          DATABASE: ${{ secrets.DATABASE }}
        run: |
          node 1pagesFromApprenticeships.js $DATE
          node 2levelJSON.js $DATE
          node 3getProviders.js $DATE
          node 4getEPAOs.js $DATE
