name: Run Apprenticeship Scripts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: npm install
        
      - name: Set Date Environment Variable
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Run Scripts
        env:
          DATABASE: ${{ secrets.DATABASE }}
        run: |
          node 3getProviders.js $DATE
          node 4getEPAOS.js $DATE
